[package]
name = "naty_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
naty_common = { path = "../naty_common" }
wry = "0.20.0"
image = "0.24.3"
toml = "0.5.9"